development:
  adapter: postgresql
  encoding: unicode
  database: circle_example
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: circle_example_test<%= ENV['TEST_ENV_NUMBER'] %>
  pool: 5
